sudo: required
services:
   - docker

before_install:
   - docker build -t rkudache31/react-test -f ./client/Dockerfile.dev ./client
script:
   docker run rkudache31/react-test npm test -- --coverage 
after_sucess:
   - docker build -t rkudache31/multi-client ./client
   - docker build -t rkudache31/multi-nginx ./nginx
   - docker build -t rkudache31/multi-server ./server
   - docker build -t rkudache31/multi-worker ./worker 
 #login my docker repository
   - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
   # take image and push
   - docker  push  rkudache31/multi-client
   - docker  push rkudache31/multi-nginx
   - docker  push  rkudache31/multi-server
   - docker push rkudache31/multi-worker
deploy:
   provider: elasticbeanstalk
   region: us-east-2
   app: Multi-Docker
   env: MultiDocker-env
   bucket_name: elasticbeanstalk-us-east-2-149157452571
   bucket_path: docker_multi
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY

